bw2023: true
ARROW:
  BLOCK_FACTOR: 0
  BLOCK_BASE: 0.5
FIREBALL:
  BLOCK_FACTOR: 0
  BLOCK_BASE: 0.5
GENERIC:
  BLOCK_FACTOR: 0
  BLOCK_BASE: 0.5
MOB_ATTACK:
  BLOCK_FACTOR: 0
  BLOCK_BASE: 0.5
PLAYER_ATTACK:
  BLOCK_FACTOR: 0
  BLOCK_BASE: 0.5
EXPLOSION:
  BLOCK_FACTOR: 0
  BLOCK_BASE: 0.5